import React, { useState, useEffect } from 'react';
import { FaLightbulb } from "react-icons/fa";
import { HiLightBulb } from "react-icons/hi";


const tips = [
  "You can earn 6x points by just holding scUSD, stkscUSD",
  "You can earn 4x points by just holding wS, S, stS, oS",
  "You can earn 5x points by just holding USDC.e",
  "Sonic's fee monetization feature allows developers to receive up to 90% of the network fees generated by their applications, providing a sustainable revenue stream.",
  "You can bridge your ETH/USDC Natively from Ethereum to Sonic by using Sonic Gateway. Transfers from Ethereum to Sonic take up to 10 minutes, while those from Sonic to Ethereum can take up to an hour.",
  "Sonic is the highest-performing EVM Layer 1, provides 10.000 TPS and sub-second finality",
  "DogBone allows you to deposit any tokens to any strategy seamlessly, without having to swap manually.",
  "You can use Earn in Portfolio Page to deploy your liquidity on protocols that can earn active points and juicy yields.",
  "You can even use any token on any chain to deposit into strategies on DogBone. If you have ETH/WBTC/USDT on Ethereum/Polygon/BSC, …, just tell DogBone and we will deploy your assets into our strategy in one transaction.",
  "You can earn up to x136 Sonic Points by depositing into DogBone-1 looping strategy.",
  "You can earn up to x72 Sonic Points by depositing into DogBone-2 looping strategy"
];

const BASE_DURATION = 1000; // base duration in ms
const PER_CHAR_DURATION = 25; // additional ms per character

const TipSection = () => {
  const [currentTipIndex, setCurrentTipIndex] = useState(0);
  const [fade, setFade] = useState('opacity-100');

  useEffect(() => {
    const currentTip = tips[currentTipIndex];
    const displayDuration = BASE_DURATION + currentTip.length * PER_CHAR_DURATION;

    const displayTimeout = setTimeout(() => {
      // Start fade out
      setFade('opacity-0');
      // After fade out animation (500ms), switch tip and fade in
      setTimeout(() => {
        setCurrentTipIndex((prev) => (prev + 1) % tips.length);
        setFade('opacity-100');
      }, 500);
    }, displayDuration);

    return () => clearTimeout(displayTimeout);
  }, [currentTipIndex]);

  return (
    <div className="relative flex items-center justify-center">
      <p className={`transition-opacity duration-500 ${fade} text-center text-lg`}>
        {tips[currentTipIndex]}
      </p>
    </div>
  );
};

const TipsBox = () => {
  return (
    <div className="flex flex-col justify-center items-center mt-10 opacity-80">
      <div
        className="p-4 rounded-2xl w-2/3 bg-(--secondary)"
      >
        <h3
          className="text-xl font-semibold mb-2 flex flex-row gap-2 items-center"
          style={{ color: 'var(--primary)' }}
        >
          <div className='text-3xl'>
          <HiLightBulb />
          </div>

          <span>Do you know?</span>
        </h3>
        <TipSection />
      </div>
    </div>
  );
};

export default TipsBox;
